### PR TITLE
[Foundation] Make it possible to customize the X509ChainPolicy when validating certificates in NSUrlSessionHandler. Fixes #23764.

### LINKED ISSUE #23764: Regression: NSUrlSessionHandler.ServerCertificateCustomValidationCallback behavior change
### Apple platform

iOS

### Framework version

net9.0-*

### Affected platform version

9.0.300

### Description

The `ServerCertificateCustomValidationCallback` has started returning a new value for `SslPolicyErrors` for the test code provided below.

### Steps to Reproduce

Repro method. This used to pass and match behavior of HttpClientHandler and SocketsHttpHandler.
```cs
        [TestMethod]
        public async Task RemoteCertificate_ForceFailure()
        {
            // Verifies that the default certificate validator is called for a normal request, and that it can be forced to fail
            int calls = 0;
            Exception callbackAssertFail = null;

#if __IOS__
            var handler = new NSUrlSessionHandler();
            handler.ServerCertificateCustomValidationCallback = (sender, certificate, chain, sslPolicyErrors) =>
#else
            var handler = new System.Net.Http.SocketsHttpHandler();
            handler.SslOptions.RemoteCertificateValidationCallback = (sender, certificate, chain, sslPolicyErrors) =>
#endif
            {
                Interlocked.Increment(ref calls);
                try
                {
                    Assert.AreEqual(SslPolicyErrors.None, sslPolicyErrors, "sslPolicyErrors"); // Fails on iOS since 9.0.300. Now returns `RemoteCertificateChainErrors`
                }
                catch (Exception ex)
                {
                    callbackAssertFail = ex;
                }
                return false;
            };

            var client = new HttpClient(handler);
            // Disable keep-alive and cache to force reconnection for each request
            client.DefaultRequestHeaders.ConnectionClose = true;
            client.DefaultRequestHeaders.CacheControl = new CacheControlHeaderValue { NoCache = true, NoStore = true };

            var responseTask = client.GetAsync(new Uri("https://sha256.badssl.com/")); // valid certificate
            try { await responseTask; }
            catch (HttpRequestException) { /* expected */ }
            
            // Expect our validator to be called once
            Assert.AreEqual(1, calls, "numCalls");
            if (callbackAssertFail != null)
            {
                throw callbackAssertFail;
            }
        }
```

### Did you find any workaround?

No

### Relevant logs

_No response_

### PR DESCRIPTION
**Pull request by rolfbjarne**
* Add a `CertificateChainPolicy` property to `NSUrlSessionHandler` to make it
  possible for developers to customize the the policy that is used when
  validating certificate chains when using a custom server certificate
  validation.
* Also implement `NSUrlSessionHandler.CheckCertificateRevocationList` using
  the new `CertificateChainPolicy` property.

Fixes https://github.com/dotnet/macios/issues/23764.

### CODE REVIEW

File: src/Foundation/NSUrlSessionHandler.cs [hunk 1]
```diff
@@ -586,15 +587,35 @@ public DecompressionMethods AutomaticDecompression {
...
+		/// <summary>Gets or sets a value that indicates whether the certificate is checked against the certificate authority revocation list.</summary>
+		/// <remarks>
+		///   <para>This is the same as setting CertificateChainPolicy.RevocationMode = X509RevocationMode.Online (if enabling the check) or X509RevocationMode.NoCheck (if disabling the check).</para>
+		///   <para>This only has an effect if a custom server certificate validation callback is being used ('ServerCertificateCustomValidationCallback' is set).</para>
+		/// </remarks>
 		[EditorBrowsable (EditorBrowsableState.Never)]
-		public bool CheckCertificateRevocationList { get; set; } = false;
+		public bool CheckCertificateRevocationList {
+			get => CertificateChainPolicy!.RevocationMode == X509RevocationMode.Online;
+			set => CertificateChainPolicy!.RevocationMode = value ? X509RevocationMode.Online : X509RevocationMode.NoCheck;
```
Comment (mandel-macaque) [inline src/Foundation/NSUrlSessionHandler.cs]: Regarding offline mode: 'Revocation checks can only be performed with cached revocation data.' 

From https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x509revocationmode?view=net-9.0

I don't think we should take care of offline since the usage is tricky. It is usually there to make the happy path faster when we have a value in the cache. I think the documentation of the remarks should be enough to let the user know.

Comment (rolfbjarne) [reply src/Foundation/NSUrlSessionHandler.cs]: @mandel-macaque I'm not sure if I understand what you're suggesting? This implementation was mostly copied from https://github.com/dotnet/runtime/blob/0e3562e97c6db531f26a2ffe3e8084cf67ba8a93/src/libraries/System.Net.Http/src/System/Net/Http/HttpClientHandler.cs#L326-L335 (I just added a comment explaining this).

Comment (bartonjs) [reply src/Foundation/NSUrlSessionHandler.cs]: Offline mode is basically a trap.  Don't use it :)
